version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    reviewers:
      - bartoszmajsak
    groups:
      k8s-core:
        dependency-type: production
        patterns:
          - "k8s.io/api"
          - "k8s.io/apimachinery"
          - "k8s.io/code-generator"        

  - package-ecosystem: "docker"
    directory: "/build"
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    reviewers:
      - bartoszmajsak

  - package-ecosystem: "github-actions"
    directory: "/" # resolved as .github/workflows
    schedule:
      interval: "weekly"
    rebase-strategy: "disabled"
    reviewers:
      - bartoszmajsak
