---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      serviceAccountName: manager
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: controller:latest
          imagePullPolicy: Always
          command:
            - /manager
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 256Mi
          env:
            - name: CONTROL_PLANE_NAME
              valueFrom:
                configMapKeyRef:
                  name: service-mesh-refs
                  key: CONTROL_PLANE_NAME
                  optional: true
            - name: MESH_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: service-mesh-refs
                  key: MESH_NAMESPACE
                  optional: true
            - name: AUTHORINO_LABEL
              valueFrom:
                configMapKeyRef:
                  name: service-mesh-refs
                  key: AUTHORINO_LABEL
                  optional: true
