apiVersion: authorino.kuadrant.io/v1beta1
kind: AuthConfig
metadata:
  name: $ODH_NS-protection
  namespace: $ODH_NS
  labels:
    authorino/topic: odh
spec:
  hosts:
  - "${ODH_ROUTE}"
  identity:
  - name: authorized-service-accounts
    kubernetes:
      audiences:
      - $ODH_NS-api
  - name: anonymous-grpc
    priority: 1
    anonymous: {}
    when:
    - selector: context.request.http.headers.mm-vmodel-id
      operator: matches
      value: .+
    extendedProperties:
    - name: modelid
      valueFrom:
        authJSON: context.request.http.headers.mm-vmodel-id
  - name: anonymous-http
    priority: 1
    anonymous: {}
    when:
    - selector: context.request.http.headers.mm-vmodel-id
      operator: matches
      value: ^$
    extendedProperties:
    - name: modelid
      valueFrom:
        authJSON: context.request.http.path.@extract:{"sep":"/","pos":2}
  metadata:
  - name: access
    http:
      endpoint: http://odh-model-controller-metrics-service.opendatahub.svc.cluster.local:8080/model/?ns={context.request.http.host.@extract:{"sep":".","pos":0}}&modelid={auth.identity.modelid}
    #cache:
    #  key:
    #    valueFrom:
    #      authJSON: {context.request.http.host.@extract:{"sep":".","pos":0}}-{auth.identity.modelid}
    #  ttl: 300
    when:
    - selector: auth.identity.anonymous
      operator: eq
      value: "true"
  authorization:
    - name: anonymous
      when:
      - selector: auth.identity.anonymous
        operator: eq
        value: "true"
      json:
        rules:
        - selector: auth.metadata.access.anonymous
          operator: eq
          value: "true"
  denyWith:
    unauthenticated:
      code: 302
      headers:
      - name: Location
        valueFrom:
          authJSON: http://some-service?redirect_to={context.request.http.path}
    unauthorized:
      code: 403
      headers:
      - name: Location
        valueFrom:
          authJSON: http://some-service?redirect_to={context.request.http.path}